[package]
name = "sxd-xml-str-comparison"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "benchmark"
harness = false

[dependencies]
sxd-xml-str = { path = ".." }
easy-ext = "1.0.0"

[dev-dependencies]
criterion = "0.5.1"
proptest = "1.0"
rand = "0.8.0"
