[package]
name = "comparison"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]
members = [
    "using-afl",
    "using-proptest",
]

[dependencies]
sxd-pull-parser = { path = "../pull-parser" }
sxd-validation = { path = "../validation" }
libxml2-sys = { path = "libxml2-sys" }
